### ISSUE TITLE
Add option to build web samples langs with gradle

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-web#109]
Currently the web sample langs cannot be build with gradle.
challenges are:

- get stuff in right order
- custom naming classes in projects

**Comment by cdietrich** [comment]
cc @holgerschill

**Comment by holgerschill** [comment]
Now we have a task generateExampleLanguages similar to xtext-core

**Comment by holgerschill** [comment]
I pushed to your branch cd_issue_109

**Comment by cdietrich** [comment]
Fixed in 2.18. thx @holgerschill
