### ISSUE TITLE
Make version numbers in generated manifests consistent with those from upstream projects

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-web#17]
The manifests for the web project are generated by Gradle, while in upstream projects they are maintained manually and post-processed for injecting the build time. The versions should be consistent.

**Comment by cdietrich** [comment]
@spoenemann i created https://github.com/eclipse/xtext-core/issues/156 for that

**Comment by spoenemann** [comment]
No, this issue is about the `Bundle-Version` entries in the MANIFEST.MF files, not the JS libs.

**Comment by cdietrich** [comment]
does that not happen automatically? i thought we use gradle to generate the manifests for all non eclipse stuff

**Comment by spoenemann** [comment]
Yes, in the web project they are generated. We should just make sure that the generated version numbers look the same as for the other projects.
