### ISSUE TITLE
Improve the Xtext Entities web example

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-web#177]
The [Xtext Entities web example](https://xtext-demo.itemis.de/orion-entities-static.html) should contain custom validation and formatting rules similar to the Xtext Domainmodel example.

**Comment by miklossy** [comment]
@Hejado will the changes be automatically reflected on the online example or does it need to be rmanually redeployed ?

**Comment by cdietrich** [comment]
you need to start https://ci.eclipse.org/xtext/job/releng/job/deploy-docker-xtext-web/

**Comment by cdietrich** [comment]
(the master jobs need to run first)

**Comment by miklossy** [comment]
I have just checked the https://xtext-demo.itemis.de/orion-entities-static.html online example and all the improvements are reflected.

**Comment by miklossy** [comment]
Fixed in 2.20
