### ISSUE TITLE
When automatically running validators, don't call expensive ones

### ISSUE THREAD

**Issue by mister-walter** [eclipse/xtext-web#212]
I have an Xtext project that contains a validator that is very expensive to call. As far as I can tell, the ValidationService automatically runs all validators (not just those with CheckType FAST or NORMAL) at initialization time.

Ideally I would like Xtext to only run validators with CheckType FAST automatically, and allow the user to provide the types of validators to run as parameters to the xtextServices.validate function. Let me know if this is already possible and I've missed it!

**Comment by cdietrich** [comment]
no you would need to customize 

```
org.eclipse.xtext.web.server.validation.ValidationService.compute(IXtextWebDocument, CancelIndicator)
```

**Comment by mister-walter** [comment]
I'm willing to try to implement this and submit a PR, but I think it will end up requiring changes to a couple other places (in particular, the cache for validation needs to be updated to reflect that validation results will depend on both the given options and the document itself). It also is not clear to me how to access the options that the user provides to the validate function - are those already exposed somewhere?

**Comment by cdietrich** [comment]
```
org.eclipse.xtext.web.server.XtextServiceDispatcher.getValidationService(IServiceContext)
```

you would have to call a different method here and pass the IServiceContext.
but that would break the api.

**Comment by mister-walter** [comment]
Thanks for your help!

I've injected the right classes on the Java side - now I need to modify the JavaScript. Is there a convenient way of editing the xtext RequireJS code without resorting to making my own copy of the webjar and hosting it? Unfortunately it seems like none of the "standard" JavaScript frameworks/packagers support webjars/the kind of RequireJS code that is used here :cry:

**Comment by cdietrich** [comment]
sorry i dont know that and i have doubts people who know read here. i guess you have to edit the code here directly
