### ISSUE TITLE
README file lacks "how to use" instructions

### ISSUE THREAD

**Issue by benblayer** [eclipse/xtext-web#224]
Hi,
Can anyone please update README so that it will be clear how to use the project?

Thanks

**Comment by cdietrich** [comment]
Hi, what exactly did not work for you.  and what do you mean by "use the project"

**Comment by benblayer** [comment]
Say I have an angular 8 project: "Users/my-user/projects/web-project" and I followed the instructions of installing xtext-web which is currently on "Users/my-user/xtext-web" and i ran "gradlew build" there.
Now I want to create some angular component "xtext-handler.component.ts" in order to create the xtext web editor there. 
What should I do?

**Comment by cdietrich** [comment]
sorry i have no idea about angular

**Comment by benblayer** [comment]
Is there any other way to get xtext-codemirror injected without RequireJS?

**Comment by cdietrich** [comment]
i dont think that anybody how knows reads here

**Comment by benblayer** [comment]
Ok. Thanks

**Comment by benblayer** [comment]
After I run gradlew build, how do I config the require.config.js file? The configuration in the reference isn't clear enough. Can you give some example please?

Thanks

**Comment by cdietrich** [comment]
Hi, i am not sure what you are doing.
if you create a new xtext project with the wizard and generate then you will get an index.html like

```
		require.config({
			baseUrl: baseUrl,
			paths: {
				"jquery": "webjars/jquery/3.4.1/jquery.min",
				"ace/ext/language_tools": "webjars/ace/1.3.3/src/ext-language_tools",
				"xtext/xtext-ace": "xtext/2.21.0-SNAPSHOT/xtext-ace"
			}
		});
		require(["webjars/ace/1.3.3/src/ace"], function() {
			require(["xtext/xtext-ace"], function(xtext) {
				xtext.createEditor({
					baseUrl: baseUrl,
					syntaxDefinition: "xtext-resources/generated/mode-mydsl1"
				});
			});
		});
```
that configs require.js inline
so which requires.config.js file are you referring to.

**Comment by benblayer** [comment]
Thanks for the quick response.
Regarding the xtext-ace path value ("xtext/2.21.0-SNAPSHOT/xtext-ace"):
What is this file and where is it located? I can't find it in the project.

**Comment by cdietrich** [comment]
the file is in the jar as the others are

![Bildschirmfoto_2020-03-04_20-12-52](https://user-images.githubusercontent.com/238736/75914175-98150680-5e54-11ea-8720-69d1b1baa151.png)

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
close as no further user feedback
