### ISSUE TITLE
PrecomputedServiceRegistry has bogus locking

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-web#231]
PrecomputedServiceRegistry has bogus locking

https://github.com/eclipse/xtext-web/pull/230/files#r415301952

getPrecomputedServices

> Must return a copy which is taken under a lock, otherwise the synchronized above is pointless.

**Comment by nbhusare** [comment]
@cdietrich Please assign this issue to me.

**Comment by cdietrich** [comment]
thx @nbhusare
