### ISSUE TITLE
Problem when placing Ace and CodeMirror editors next to each other

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-web#239]
I observed the following problem when placing an `Ace` and a `CodeMirror` editor next to each other.
![screencast](https://user-images.githubusercontent.com/20393472/83051967-f9f99c80-a04e-11ea-804d-0af4817ba15d.gif)

**Comment by miklossy** [comment]
The problem can be reproduced when checking out the [miklossy_master_issue_239](https://github.com/eclipse/xtext-web/tree/miklossy_master_issue_239) branch.

**Comment by miklossy** [comment]
**Hint:** When removing the [following line](https://github.com/eclipse/xtext-web/blob/66ce8fb5fc7825b3029ca365b14fdc127aa2c7f2/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-and-codemirror-statemachine.html#L6), the problem does not occur.
![screencast2](https://user-images.githubusercontent.com/20393472/83053121-86f12580-a050-11ea-8863-c640790964ce.gif)

**Comment by cdietrich** [comment]
do you think the both csses conflict with each other?

**Comment by miklossy** [comment]
Yes. I thinkt the two xtext ace and xtext codemirror css files conflict each other.

**Comment by cdietrich** [comment]
will close this for now as rare usecase
