### ISSUE TITLE
Jetty locks files on Windows

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-web#240]
Whenever trying to save a file that has been changed while the Jetty server is running, a `Save Problem` occurs, since Jetty locks the files.
![screencast](https://user-images.githubusercontent.com/20393472/83287709-65c03e80-a1e2-11ea-93ec-f76d451a0fd0.gif)
This problem has already been reported ([#489574](https://bugs.eclipse.org/bugs/show_bug.cgi?id=489574)) and fixed ([commit](https://github.com/eclipse/xtext-core/commit/d1b582f3f85fcde69b5200d2d48ecbf7f501435e)), but seems that the fix does not hold any more.

**Hint:** when renaming the parameter key from `org.mortbay.jetty.servlet.Default.useFileMappedBuffer` to `org.eclipse.jetty.servlet.Default.useFileMappedBuffer`, the desired affect can be reached, see the corresponding [stackoverflow post](https://stackoverflow.com/questions/13615123/embedded-jetty-server-8-and-eclipse-ide-on-windows-7-cannot-save-file).

I would suggest to rename the key in the WebIntegrationFragment on the following two occurrences: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend#L698 and https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend#L742

**Comment by cdietrich** [comment]
@miklossy anything left?

**Comment by miklossy** [comment]
Nothing is left. Thanks for reminding me.
Fixed in 2.23.
