### ISSUE TITLE
Xtext Web 2.25.0 release?

### ISSUE THREAD

**Issue by MarcMil** [eclipse/xtext-web#291]
Since XText main is 2.25.0 and uses a newer version of Guava and XText Web 2.24.0 uses specifically an older release, these two cannot work together. Is a release planned for Xtext Web or has it been silently ditched, as I could not find anything in the release notes?

**Comment by cdietrich** [comment]
hi, how do you conclude that xtext-web uses older guava?

**Comment by cdietrich** [comment]
![Bildschirmfoto 2021-04-07 um 13 10 03](https://user-images.githubusercontent.com/238736/113857278-9c6fc980-97a2-11eb-87d2-f3553c5afaa5.png)

**Comment by MarcMil** [comment]
Interesting. Is it also published on the update site?
Our build process based on Tycho states 
```
Missing requirement: xyz 1.0.0.qualifier requires 'osgi.bundle; org.eclipse.xtext.web.servlet 2.25.0' but it could not be found
```
when we try to reference the new version using the XText update site.
Meanwhile, the xtext main branch is available on the update site. It however can access and retrieve XText Web 2.24.0 apparently.
Interestingly, on neither http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.24.0/plugins/ nor http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.25.0/plugins/ there are any mentions on XText Web. Does XText Web use some other update site I am not aware of?

**Comment by cdietrich** [comment]
Xtext-Web was never published to the update site

**Comment by cdietrich** [comment]
do you do some use maven dependencies in tycho? some tycho 2.x feature?

**Comment by MarcMil** [comment]
Oh, it seems that you're right. Thanks for the really fast response! It seems that we use the Maven reficio plugin to package it ourselves. I need to adapt the version number there as well of course.
I somehow believed that it was also published as an eclipse plugin like the other XText components, but it seems I recalled wrong. Thank you very much for that hint :)
