### ISSUE TITLE
Orion: require orion/code_edit/built-codeEdit-amd.js fails

### ISSUE THREAD

**Issue by RobertWalter83** [eclipse/xtext-web#3]
Hi all,

using the bare-bone web project generated by the Xtext wizard (v. 2.10.0) and trying to use the Orion Editor, I get this error:

![orionfail](https://cloud.githubusercontent.com/assets/5462981/16196532/ad16d1ac-36fe-11e6-83e9-256bcd6cd488.png)

**Comment by cdietrich** [comment]
@RobertWalter83 the docs say you have to provide orion yourself since there is no webjars.
did you do that or simply adapted the workflow?

**Comment by spoenemann** [comment]
Please reopen if the issue is something different from what @cdietrich described.
