### ISSUE TITLE
CodeMirror binds formatting to Ctrl+Shift+S

### ISSUE THREAD

**Issue by richardmward** [eclipse/xtext-web#31]
I noticed that the formatting service didn't appear to work with CodeMirror, and having had a quick glance at the source I think the keymap is incorrectly binding Ctrl+Shift+S rather than Crtl+Shift+F on Windows.

**Comment by cdietrich** [comment]
well it is explicitely binding it

```
services.formatKeyMap = /mac os/.test(userAgent) ? {'Shift-Cmd-F': formatFunction}: {'Shift-Ctrl-S': formatFunction};
```

the questions are

- why?
- can this be changed or should the documentation be updated

**Comment by cdietrich** [comment]
maybe cause it collides with

```
replace Shift-Ctrl-F (PC), Cmd-Alt-F (Mac)
```
in CodeMirror

**Comment by richardmward** [comment]
I see, well, I was just flagging it up as it does not do what the docs say.

**Comment by cdietrich** [comment]
@spoenemann what do you think? simply update the docs / js comments?

**Comment by richardmward** [comment]
I don't know if it is feasible to have this updated as being the case on for CodeMirror on https://www.eclipse.org/Xtext/documentation/330_web_support.html too? I know that the only reason I started looking in the source was because it wasn't working - i'd have otherwise have been using that webpage.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext/commit/32634000f42fbee87d94e34812514006f11a7962

**Comment by cdietrich** [comment]
documentenation updated
