### ISSUE TITLE
Error 404 when using accessing xtext services in a cross domain situation

### ISSUE THREAD

**Issue by alfrye** [eclipse/xtext-web#39]
When the code mirror editor is being served by on domain and the backend xtext services are being hosted on different domain and you enable the CORS filter inside of jetty the Chrome browser after version 45 does not allow the cookie to be saved, therefore every request to the xtext services create a new session. According to CORS documentation in order to have the browser to save the cross domain cookie you can add the following code to the jquery request 
`crossDomain: true,
 xhrFields: {
   withCredentials: true
}`  You also need to make sure that the server is setting the proper response headers in the response back to the browser.

**Comment by spoenemann** [comment]
Client-side is handled in [XtextSevice.js](https://github.com/eclipse/xtext-web/blob/master/org.eclipse.xtext.web/src/main/js/xtext/services/XtextService.js#L164), server side is handled in [XtextServlet.xtend](https://github.com/eclipse/xtext-web/blob/master/org.eclipse.xtext.web.servlet/src/main/java/org/eclipse/xtext/web/servlet/XtextServlet.xtend#L128).

**Comment by alfrye** [comment]
I was able to find the Client-Side code and added the code to there. For the server side I have tried to use the Jetty Servlet filters in order to set the appropriate response headers for the request, so that i would have to modified the XtextServletxtend code. I will look into the XtextServlet.xtend code to see if I can get that to work.

**Comment by cdietrich** [comment]
added documentation here: https://github.com/eclipse/xtext/commit/b8499b3c3c03b72f3566395dafd557ae8069e66f
