### ISSUE TITLE
Status 404: CodeMirror

### ISSUE THREAD

**Issue by RobertWalter83** [eclipse/xtext-web#4]
Using the bare-bone web project generated by the Xtext wizard (2.10.0), trying to use the CodeMirror editor, fails to find webjars js files for CodeMirror:

![codemirrorfail](https://cloud.githubusercontent.com/assets/5462981/16196879/0890a50c-3700-11e6-90cf-0eeb3c4ba673.png)

**Comment by cdietrich** [comment]
@holgerschill i asume we should "fix" this by adding a hint to the docs to adapt the gradle or pom right?

**Comment by cdietrich** [comment]
Alternatively we could add CM and ace webjars by default

**Comment by spoenemann** [comment]
The wizard generates Ace support, which is the default of StandardLanguage. If you want CodeMirror, you have to adapt the build.gradle accordingly. We could make this more clear in the documentation.
