### ISSUE TITLE
Completion doesn't work consistently in web editor

### ISSUE THREAD

**Issue by mvmn** [eclipse/xtext-web#64]
## Steps to reproduce
In Xtext 2.14, given a simple grammar like
```
grammar x.mvmn.tmpxtextproj.TemporaryXtextProject with org.eclipse.xtext.common.Terminals

generate temporaryXtextProject "http://www.mvmn.x/tmpxtextproj/TemporaryXtextProject"

Model:
	greetings+=Greeting*;

Greeting:
	'$' name=('a' | 'b' | 'c') | '@' name=('x' | 'y' | 'z');
```
Generate web editor (which uses Ace editor by default) and try invoking code completion for inputs "\@" and "\$" (one character input in both cases - don't include quotes).

## Expected result
- Completion for input \@ returns options  x, y and z
- Completion for input \$ returns options a, b and c.

## Actual result
- Completion for input \@ returns options \@, x, y and z
- Completion for input \$ returns nothing

## Issue details
Server responses for /xtest-service/assist in both cases are practically the same:
```
{
    "stateId": "-7ffffffa",
    "entries": [
        {
            "prefix": "",
            "proposal": "x",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "y",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "z",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "@",
            "proposal": "@",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        }
    ]
}
```

```
{
    "stateId": "-7ffffff8",
    "entries": [
        {
            "prefix": "",
            "proposal": "a",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "b",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "c",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "$",
            "proposal": "$",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        }
    ]
}
```

Debugging shows that this behaviour is the case because \$ is considered to be pre-existing prefix, and completions are filtered using that prefix. For \@ this is not the case though.

Further debugging reveals that this is happening due to Ace editor function for retrieving preceding identifier, which uses hardcoded regexp `/[a-zA-Z_0-9\$\-\u00A2-\uFFFF]/` that includes \$ but does not include \@.
Here is the corresponding code from /webjars/ace/1.2.3/src/ext-language_tools.js
```
var ID_REGEX = /[a-zA-Z_0-9\$\-\u00A2-\uFFFF]/;

exports.retrievePrecedingIdentifier = function(text, pos, regex) {
    regex = regex || ID_REGEX;
    var buf = [];
    for (var i = pos-1; i >= 0; i--) {
        if (regex.test(text[i]))
            buf.push(text[i]);
        else
            break;
    }
    return buf.reverse().join("");
};
```

! Note: adding space after \@ or \$ produces expected result. 
It is not clear though why serverside code returns different completions for just \@ or \$ and for the same input plus extra space.

**Comment by cdietrich** [comment]
@mvmn what i dont get: what do you mean by server side "completions for just @ or $ and for the same input plus extra space."

**Comment by mvmn** [comment]
Hi @cdietrich 

There are two issues here:
1. On a client-side there is some regexp based filtering, purpose of which is not clear. It might be "easy" to modify that regexp (I'm writing easy in quotes because technically it is of course very simple to change that line in a JS file - but if that'll create your own fork of Ace editor than you might want to think twice before doing such a thing), but - before modifying it there is a need to understand why it is there and what is that filtering doing. The filtering might be removed completely, but I'm guessing it's there for a reason.
2. On a server-side there is a different response when doing completion for input "@" (single at-sign) and input "@ " (at-sign followed by a space). Same for "$" and "$ ". In first case (no space after @ or $) we get expected completion plus the symbol itself (e.g. a,b,c,$ for input "$" and x,y,z,@ for input "@"), in second case (@ or $, followed by a space) we get expected completion (e.g. a,b,c for "$ " and x,y,z for "@ ").

**Comment by cdietrich** [comment]
the problem here is ace. and i did not find a "easy" way on the first glance but i am not a JS wizard.
i did some server side debugging and i dont get different responses for `$<|>` and `@<|>`
and of course the " " breaks the server side prefixes so it starts from "fresh" and thus you will get the letters.

**Comment by mvmn** [comment]
I have tried it again, and I'm getting different responses for "@" and "@ ".

> the " " breaks the server side prefixes
I'm sorry, but I'm not sure what this means - I'm not that familiar with the internals of Xtext.

**Comment by cdietrich** [comment]
i dont know what ace guys intention for the prefix stuff is.

on server side:
`@` you get `@` the current, and zyx the followers
for `@ ` you get (actually not delivered) the ` ` and the and zyx the followers

=> the problem is how the client treats this stuff
=> if you ly in the proposal provider

```
package org.xtext.example.mydsl.ide

import org.eclipse.xtext.Keyword
import org.eclipse.xtext.ide.editor.contentassist.ContentAssistContext
import org.eclipse.xtext.ide.editor.contentassist.ContentAssistEntry
import org.eclipse.xtext.ide.editor.contentassist.IIdeContentProposalAcceptor
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider

class MyDslIdeContentProposalProvider extends IdeContentProposalProvider {
	override protected void _createProposals(Keyword keyword, ContentAssistContext context,
		IIdeContentProposalAcceptor acceptor) {
		var boolean _filterKeyword = this.filterKeyword(keyword, context)
		if (_filterKeyword) {
			val ContentAssistEntry entry = this.proposalCreator.createProposal(keyword.getValue(), context)
			if ((entry !== null)) {
				if (context.prefix == "" && "a" == keyword.value) { // use constants in MydslGrammarAccess
					entry.prefix = "$"
					entry.proposal = "$" + entry.proposal
					entry.label = "a"
				}
				System.err.println(context.prefix)
				entry.setKind(ContentAssistEntry.KIND_KEYWORD)
				acceptor.accept(entry, this.proposalPriorities.getKeywordPriority(keyword.getValue(), entry))
			}
		}
	}
}
```
you could mitigate the ace flaws on server side
